baseURL = "https://theiberg.github.io/jamsite/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Enso.ai"
disableKinds = ["section"]

[outputs]
    home = ["JSON", "HTML"]