baseURL = "https://inspiring-mcclintock-aa0a5e.netlify.app"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Enso.ai"
disableKinds = ["section"]

[outputs]
    home = ["HTML", "JSON"]